name: Python-pre-releases

# Run this workflow every time a new commit pushed to your repository
# on: push

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     python-version: [ '2.x', '3.x', 'pypy2', 'pypy3' ]
    name: Python pre-release test
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.0-alpha - 3.10.0' # SemVer's version range syntax
      - run: python -c "print('hi')""
      - run: python -v
